server:
  port: 8081

spring:
  application:
    name: producto-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 90
    renewal-percent-threshold: 0.85
    enable-self-preservation: true
